import Head from 'next/head'
import Component from './component'
import { SecondComponenet } from './component'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { use, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })
function Mybutton(){
  return(
    <button>
      start
    </button>

  )
}
const user = {
  name: 'Hedy Lamarr',
  imageUrl: 'https://i.imgur.com/yXOvdOSs.jpg',
  imageSize: 90,
};
const products = [
  { title: 'Cabbage', id: 1 },
  { title: 'Garlic', id: 2 },
  { title: 'Apple', id: 3 },
];

const items= products.map(item=>
  <li key = {item.id}>

    {item.title}</li>
)


export default function Home() {
  const [  count, setCount]= useState(0)

  function handelClick(){
    setCount(c=>c*2)
  }
  function reSet(){
    setCount(1)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div>
          <SecondComponenet name ="Sami"/>
          <SecondButton className="background: red"/>         
          <Component/> 
          <Component/> 
          <Component/> 

        </div>
        <div className={styles.helloworld}>
          <h1>Hellow world From React new app</h1>
          <Mybutton/>
          <MybuttonCount  count={count} onClick={handelClick}/>
          <MybuttonCount  count={count} onClick={handelClick}/>
          <MybuttonCount  count={count} onClick={handelClick}/>
          <button onClick={handelClick}> Count {count} times </button>
          <button onClick={reSet} >reset</button>
        </div>
        <div style={{alignItems:'right'}}>
          <h1>Name: {user.name}</h1>
          <img
          src={user.imageUrl}
          alt={user.name}
          style={{
             height : user.imageSize,
             width : user.imageSize
                }}  
          />
          <ul>
            {items}
          </ul>
        </div>
        
      </main>
    </>
  )
}

 function MybuttonCount( {count, onClick}){
  
  
  return(
    <button onClick={onClick}>
      Count {count} times
    </button>
  )
 }
 function SecondButton(){
  return (
    <button > This is My Second button </button>
  )
 }
